img_h: 352
img_w: 352
batch_size: 32
train_img_size:
  - [352, 352]
  - [320, 320]
  - [288, 288]
  - [384, 384]
  - [416, 416]
yolo:
  num_classes: 20
  num_anchors: 3
  iou_thres: [0.7, 0.5]
  anchors:
  - [143, 265]
  - [153, 121]
  - [280, 279]
  - [20, 37]
  - [49, 94]
  - [73, 201]
  classes: 20
  mask:
  - [0, 1, 2]
  - [3, 4, 5]
